### ISSUE TITLE
[IP] 3rd party dependencies issues to solve

### ISSUE THREAD

**Issue by phkrief** [eclipse-researchlabs/smartclide-td-reusability-theia#2]
I found some potential issues with some of your dependencies:

| Dependency                                                                                   | License                    |
| npm/npmjs/@amcharts/amcharts4/4.10.22			               | Free amCharts        |
| npm/npmjs/@devexpress/dx-chart-core/2.7.6			       | DevExpress            |
| npm/npmjs/@devexpress/dx-core/2.7.6				       | DevExpress            |
| npm/npmjs/@devexpress/dx-react-chart-bootstrap4/2.7.6      | DevExpress            |
| npm/npmjs/@devexpress/dx-react-chart-material-ui/2.7.6       | DevExpress            |
| npm/npmjs/@devexpress/dx-react-chart/2.7.6		               | DevExpress            |
| npm/npmjs/@devexpress/dx-react-core/2.7.6			       | DevExpress            |

None of these licenses are open source licenses recognized by the Open Source Initiative (https://opensource.org/licenses/alphabetical).
So your code will be de facto rejected because it is not "business-friendly".

Do you have other choices?
Thx

**Comment by phkrief** [comment]
Fixed ! Thx

**Comment by nikosnikolaidis** [comment]
@phkrief it seems that I missed this issue! I am  sorry for the delay!

The "devexpress" dependences can be deleted, so there shouldn't be a problem.
As for the "amcharts", if there is still a problem I will try to find another library in order to replace it.

**Comment by phkrief** [comment]
My apologies. I closed the issue because I tool could not find it anymore. Actually, it was a bug in my tool :-)...
So I reopen it.

**Comment by nikosnikolaidis** [comment]
@phkrief I found an alternative library that works for us and it seems to be ok from the license aspect.
Could you also confirm, in order to continue with the implementation?

Thx

**Comment by phkrief** [comment]
@nikosnikolaidis are you talking about victory-canvas/36.2.0 ?
You are correct. It seems that this library is shared under the MIT license which is compatible with the EPL 2.0 license.
So it should work fine.
Because it is unknown by the Eclipse IP and the ClearlyDefined repositories, we will have to fill a Contributor Questionnaire (CQ) which will be accepted, nothing more.
Thx

**Comment by nikosnikolaidis** [comment]
@phkrief the library is victory/36.2.0 and I was able to find it in ClearlyDefined.
The victory-canvas, victory-chart, victory-core, etc. are just some inner packages of this library.
